### ISSUE TITLE
Prompt Password

### ISSUE THREAD

**Issue by Micene09** [mkloubert/vs-deploy#79] opened 2017-06-01 09:32 UTC
Hi,
First of all,  i have to say that this extension is awesome...but one of the most usefull options is the prompt for password popup, when there is no password provided in settings.json .

I think is a must have, especially for secure environment, where the password will never be readable.

Because of this missing feature, i cannot use it at work right now.

**Comment by mkloubert** [comment] 2017-06-01 20:10
@Micene09 

For what kind of [targets](https://github.com/mkloubert/vs-deploy/wiki#targets-)?

**Comment by imanilchaudhari** [comment] 2017-06-02 03:33
@mkloubert  yeah I need that too. I think @Micene09 is talking about sftp target.

**Comment by mkloubert** [comment] 2017-06-04 10:58
@Micene09 @imanilchaudhari 

**I released version 9.15.0 that will now prompt an input box for [sftp targets](https://github.com/mkloubert/vs-deploy/wiki/target_sftp), if no password is defined.**

This will happen by default if you DO NOT use a private key file (`privateKeyPassphrase` setting).

If you use such a file (and want to use that feature), you also have to set `promptForPassword` to `(true)`.

I will also implement this for the other targets the next days.

**Comment by Micene09** [comment] 2017-06-04 11:16
@mkloubert 
Wao! Thank you for this fast implementation!
Sorry if i'm late but, i was so busy at work...
BTW, right now i need it for the FTP target (i'm using it with option secure: true), just because the FTP server, where i need to upload is in a LAN.

I think that, having the prompt for password on all targets possible, should be a very nice feature.

Thank you again!

**Comment by imanilchaudhari** [comment] 2017-06-04 11:50
@mkloubert Thanks it is amazing. But there seem some bugs. Password prompt box is asking for three times. And by the way this will be great if you use some session or cache storage for password. Sublime's [sftp](https://wbond.net/sublime_packages/sftp) has really good feature.

**Comment by mkloubert** [comment] 2017-06-04 12:32
@imanilchaudhari 

3 times for 3 connections or 3 times for one connection?

**Comment by imanilchaudhari** [comment] 2017-06-04 13:14
@mkloubert 3 times for one connection. While I was trying to deploy a single file. Nevertheless rest is working fine.

**Comment by mkloubert** [comment] 2017-06-04 14:34
@Micene09 @imanilchaudhari 

I released [version 9.16.0](https://github.com/mkloubert/vs-deploy/releases/tag/v9.16.0) that now contains all feature, like password prompt for FTP and password caching.

@imanilchaudhari I cannot reproduce the issue. Maybe it is fixed with the new version.

If not: Can you post an example config? Btw: Do you use things like [each](https://github.com/mkloubert/vs-deploy/wiki/target_each) or [map](https://github.com/mkloubert/vs-deploy/wiki/target_map)?

**Closed** 2017-06-04 16:26 UTC
Labels: enhancement

**Comment by Micene09** [comment] 2017-06-04 16:29
Thank you for this new release, I'm ok with the goal of this issue.

Closing.

**Comment by imanilchaudhari** [comment] 2017-06-04 18:11
@mkloubert Thank you. It is working fine with this release.
