### ISSUE TITLE
SFTP deploying with undesirable file/directory permissions

### ISSUE THREAD

**Issue by hazzlewis** [mkloubert/vs-deploy#61] opened 2017-04-21 13:00 UTC
Hi, ive looked through the wiki and I dont think there's a way to override the permissions that deploy uses to create files and folders on the target host. 

Is it possible to change this?

**Comment by mikes-gh** [comment] 2017-04-21 14:33
According to the sftp client that is used this should be possible 
https://github.com/jyu213/ssh2-sftp-client/issues/5
It would require some changes is vs-deploy though.

**Comment by mkloubert** [comment] 2017-04-27 18:37
@mikes-gh Thank you very much for the help! The name `useCompression` of the third argument is very misleading.

@hazzlewis 

**Since version 8.11.0 you are now able to use the `modes` setting in your [sftp](https://github.com/mkloubert/vs-deploy/wiki/target_sftp) targets,**

You can do this in 2 ways:

1.) for all files:

```json
{
    "deploy": {
        "targets": [
            {
                "type": "sftp",

                // ...

                "modes": 666
            }
        ]
    }
}
```

2.) for specific files using [regular expressions](https://en.wikipedia.org/wiki/Regular_expression):

```json
{
    "deploy": {
        "targets": [
            {
                "type": "sftp",

                // ...

                "modes": {
                    "(\\.html)$": 777,
                    "(\\.php)$": 666,
                }
            }
        ]
    }
}
```

HINT: The values that are tested with the regular expressions are the TARGET file paths!

**All values are OCTAL as you know that from [chmod](https://en.wikipedia.org/wiki/Chmod).**

**Comment by hazzlewis** [comment] 2017-04-27 20:07
Thanks I'll use this for files. But what about directories??


Kind Regards
Harry Lewis


-------- Original message --------

**Comment by mkloubert** [comment] 2017-04-27 21:35
@hazzlewis 

What's with the new [Execute commands on server](https://github.com/mkloubert/vs-deploy/wiki/target_sftp#execute-commands-on-server) feature (since 8.12.0).

**Comment by parente** [comment] 2017-06-15 13:28
Thank you for adding various options for adjusting modes on the target. I've been struggling to use them and was wondering if anyone else is seeing the same behavior. 

* My SFTP server is configured to disallow execution of arbitrary commands, so the new "execute commands on server" option does not work (as expected).
* I've tried using the `modes` attribute with a fixed int, a string, and an object with regular expressions, but none of them have any impact on the mode after transfer.

For example:

```
...
"targets" : {
...
   "modes": 700
...
}
```

still results in:

```
...
drwxrwxrwx 2 p-pparente users  4096 Jun 15 13:24 dist
drwxrwxrwx 2 p-pparente users  4096 Jun 15 13:24 examples
-rw-rw-rw- 1 p-pparente users    36 Jun 15 13:24 requirements-test.txt
-rw-rw-rw- 1 p-pparente users    54 Jun 15 13:24 requirements.txt
-rw-rw-rw- 1 p-pparente users   513 Jun 15 13:24 run_tests.py
...
```

I dug through the source here a bit to see if I could spot what I am doing wrong, but nothing jumps out at me from the logic here https://github.com/mkloubert/vs-deploy/blob/f5a4b730b1c65401bc761765a501c4282c619071/src/plugins/sftp.ts#L520.

I did confirm that running `sftp` from the command line and using the `chmod` command in an open session works as expected.

**Comment by hazzlewis** [comment] 2017-06-15 14:04
I get inconsistent results depending on the server also. Makes me miss sublime sftp.



-------- Original message --------

**Comment by mkloubert** [comment] 2017-06-16 12:23
@parente @hazzlewis 

Sorry for the late answer.

I found the mistake with the [modes](https://github.com/mkloubert/vs-deploy/wiki/target_sftp#modes-for-specific-files).

**Since version 9.16.0** the client of the [SFTP target](https://github.com/mkloubert/vs-deploy/wiki/target_sftp) will now do the `chmod` after it has uploaded a file, and NOT execute a [command](https://github.com/mkloubert/vs-deploy/wiki/target_sftp#execute-commands-on-server), s. [sftp.ts](https://github.com/mkloubert/vs-deploy/blob/master/src/plugins/sftp.ts#L731).

On my [vagrant](https://en.wikipedia.org/wiki/Vagrant_(software)) test machine it works as expected and should also run on "real" systems.

**Comment by parente** [comment] 2017-06-16 15:43
@mkloubert Awesome. Thanks for fixing this so quickly. I can confirm `"modes": 644` chmod's the files properly now. Directories are 777 no matter what it seems.

```
drwxrwxrwx 2 p-pparente users  4096 Jun 16 15:35 dist
drwxrwxrwx 2 p-pparente users  4096 Jun 16 15:35 examples
-rw-r--r-- 1 p-pparente users    36 Jun 16 15:35 requirements-test.txt
-rw-r--r-- 1 p-pparente users    54 Jun 16 15:35 requirements.txt
-rw-r--r-- 1 p-pparente users   513 Jun 16 15:35 run_tests.py
```

**Comment by mkloubert** [comment] 2017-06-16 16:51
@parente 

Of, course ... directories should also be updated.

**I made a small release 9.26.1 and added the `updateModesOfDirectories` setting:**

```
...
"targets" : {
...
   "modes": 700,

   "updateModesOfDirectories": true
...
}
```

If set to `(true)`: This will also do a `chmod` for the directory of a file that is going to be uploaded.

**Comment by AdsonCicilioti** [comment] 2018-03-20 22:13
My question is similar.

My destination directory can only be written by user **X**. Is there any option to send a command writing like this user?

**Comment by mkloubert** [comment] 2018-03-21 08:45
s. [Allow write like as specific user/permission](https://github.com/mkloubert/vscode-deploy-reloaded/issues/51) @ [vscode-deploy-reloaded](https://github.com/mkloubert/vscode-deploy-reloaded)

**Closed by mkloubert** 2018-03-21 08:45 UTC
Labels: enhancement
